import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import QuoteTemplate from './QuoteTemplate';

const items = [
  {
    serialNo: 1,
    articleCode: '534.84.523',
    articleName: 'Teresa Neo Hood',
    category: 'Cooker Hoods',
    mrp: 90290,
    rrp: 68990,
    dealerPricePreTax: 46254,
    dealerPricePostTax: 54580,
    quantity: 2,
    lineTotal: 109160,
    origDealerPreTax: 46254,
    origDealerPostTax: 54580,
    adjDealerPreTax: 54000,
    adjDealerPostTax: 64000,
    adjLineTotal: 128000,
    origLineTotal: 109160,
    isOverridden: false,
  },
];
const totals = {
  totalMRP: 180580,
  totalRRP: 137980,
  totalDealerPreTax: 92508,
  totalDealerPostTax: 109160,
};
const baseProps = {
  quoteTitle: 'Smart Quote Generator',
  items,
  totals,
  templateType: 'detailed',
  hasOverride: false,
};

describe('QuoteTemplate — never shows sensitive data', () => {
  it('never renders margin %', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.queryByText(/\bmargin\b/i)).not.toBeInTheDocument();
  });

  it('never renders expiry', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.queryByText(/expir/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/valid for/i)).not.toBeInTheDocument();
  });

  it('never renders cost / avgLanding', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.queryByText(/avg landing/i)).not.toBeInTheDocument();
  });

  it('never renders a QT- quote number (#18)', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.queryByText(/QT-\d+/)).not.toBeInTheDocument();
  });

  it('never renders Line Total column (#4)', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.queryByText(/line total/i)).not.toBeInTheDocument();
  });
});

describe('QuoteTemplate — detailed template', () => {
  it('renders title', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.getAllByText('Smart Quote Generator').length).toBeGreaterThan(0);
  });

  it('renders article code', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.getByText('534.84.523')).toBeInTheDocument();
  });

  it('renders TOTALS in tfoot (#3)', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.getByText('TOTALS')).toBeInTheDocument();
  });

  it('renders Dealer Pre-Tax column header (#20)', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.getByText('Dealer Pre-Tax')).toBeInTheDocument();
  });

  it('renders header and footer', () => {
    render(<QuoteTemplate {...baseProps} />);
    expect(screen.getByText(/Generated by/i)).toBeInTheDocument();
  });

  it('shows Adjusted label when hasOverride', () => {
    render(<QuoteTemplate {...baseProps} hasOverride={true} />);
    expect(screen.getByText('Adjusted')).toBeInTheDocument();
  });

  it('accepts a ref', () => {
    const ref = { current: null };
    render(<QuoteTemplate ref={ref} {...baseProps} />);
    expect(ref.current).not.toBeNull();
  });
});

describe('QuoteTemplate — simple template (#8)', () => {
  it('does NOT render header section', () => {
    render(<QuoteTemplate {...baseProps} templateType="simple" />);
    // Should not show the title in the header section
    expect(screen.queryByText(/Generated by/i)).not.toBeInTheDocument();
  });

  it('renders plain table with TOTALS', () => {
    render(<QuoteTemplate {...baseProps} templateType="simple" />);
    expect(screen.getByText('TOTALS')).toBeInTheDocument();
  });

  it('still renders column headers', () => {
    render(<QuoteTemplate {...baseProps} templateType="simple" />);
    expect(screen.getByText('Dealer Pre-Tax')).toBeInTheDocument();
  });
});
