import { forwardRef } from 'react';
import PropTypes from 'prop-types';
import { formatCurrency, formatDateShort } from '../../utils/formatters';
import { APP_NAME } from '../../constants/columnMap';
import styles from './QuoteTemplate.module.css';

/**
 * QuoteTemplate — rendered off-screen and captured by html2canvas.
 *
 * IMPORTANT:
 * - marginPercent is NEVER accepted as a prop and NEVER rendered.
 * - No expiry date is shown anywhere.
 * - Quote number format: QT-<long integer timestamp>
 *
 * Props items shape: { serialNo, articleCode, articleName, category,
 *   mrp, rrp, dealerPricePreTax, gstRate, dealerPricePostTax, quantity, lineTotal }
 * No marginPercent field should exist on any item.
 */
const QuoteTemplate = forwardRef(function QuoteTemplate({ quoteNumber, items, totals }, ref) {
  const today = formatDateShort(new Date());

  return (
    <div ref={ref} className={styles.template}>
      {/* Header */}
      <div className={styles.header}>
        <h1 className={styles.appName}>{APP_NAME}</h1>
        <div className={styles.headerMeta}>
          <div className={styles.metaItem}>
            <span className={styles.metaLabel}>Quote No</span>
            <span className={styles.metaValue}>{quoteNumber}</span>
          </div>
          <div className={styles.metaItem}>
            <span className={styles.metaLabel}>Date</span>
            <span className={styles.metaValue}>{today}</span>
          </div>
        </div>
      </div>

      {/* Items Table */}
      <table className={styles.table}>
        <thead>
          <tr className={styles.tableHead}>
            <th className={styles.thSr}>#</th>
            <th className={styles.thCode}>Article Code</th>
            <th className={styles.thName}>Product</th>
            <th className={styles.thQty}>Qty</th>
            <th className={styles.thAmount}>MRP</th>
            <th className={styles.thAmount}>RRP</th>
            <th className={styles.thAmount}>Dealer Post-Tax</th>
            <th className={styles.thAmount}>Line Total</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, index) => (
            <tr key={item.articleCode || index} className={styles.tableRow}>
              <td className={styles.tdSr}>{index + 1}</td>
              <td className={styles.tdCode}>{item.articleCode}</td>
              <td className={styles.tdName}>
                <span className={styles.itemName}>{item.articleName}</span>
                <span className={styles.itemCategory}>{item.category}</span>
              </td>
              <td className={styles.tdQty}>{item.quantity}</td>
              <td className={styles.tdAmount}>{formatCurrency(item.mrp)}</td>
              <td className={styles.tdAmount}>{formatCurrency(item.rrp)}</td>
              <td className={styles.tdAmount}>{formatCurrency(item.dealerPricePostTax)}</td>
              <td className={`${styles.tdAmount} ${styles.lineTotal}`}>
                {formatCurrency(item.lineTotal)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Totals */}
      <div className={styles.totalsSection}>
        <div className={styles.totalsGrid}>
          <div className={styles.totalRow}>
            <span className={styles.totalLabel}>Total MRP</span>
            <span className={styles.totalValue}>{formatCurrency(totals.totalMRP)}</span>
          </div>
          <div className={styles.totalRow}>
            <span className={styles.totalLabel}>Total RRP</span>
            <span className={styles.totalValue}>{formatCurrency(totals.totalRRP)}</span>
          </div>
          <div className={styles.totalRow}>
            <span className={styles.totalLabel}>Total Dealer Price (Pre-Tax)</span>
            <span className={styles.totalValue}>{formatCurrency(totals.totalDealerPreTax)}</span>
          </div>
          <div className={`${styles.totalRow} ${styles.totalRowFinal}`}>
            <span className={styles.totalLabel}>Total Dealer Price (Post-Tax)</span>
            <span className={`${styles.totalValue} ${styles.finalValue}`}>
              {formatCurrency(totals.totalDealerPostTax)}
            </span>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className={styles.footer}>
        <p className={styles.footerText}>Generated by {APP_NAME}</p>
      </div>
    </div>
  );
});

QuoteTemplate.propTypes = {
  quoteNumber: PropTypes.string.isRequired,
  items: PropTypes.arrayOf(
    PropTypes.shape({
      articleCode: PropTypes.string,
      articleName: PropTypes.string,
      category: PropTypes.string,
      mrp: PropTypes.number,
      rrp: PropTypes.number,
      dealerPricePreTax: PropTypes.number,
      gstRate: PropTypes.number,
      dealerPricePostTax: PropTypes.number,
      quantity: PropTypes.number,
      lineTotal: PropTypes.number,
      // marginPercent is intentionally absent — never passed to this component
    })
  ).isRequired,
  totals: PropTypes.shape({
    totalMRP: PropTypes.number,
    totalRRP: PropTypes.number,
    totalDealerPreTax: PropTypes.number,
    totalDealerPostTax: PropTypes.number,
  }).isRequired,
};

QuoteTemplate.displayName = 'QuoteTemplate';
export default QuoteTemplate;
